baseURL = "/"
languageCode = "en-us"
title = "Logan Egbert"
description = "Portfolio Website of Logan Egbert"
theme = "minimal"
publishDir ="docs"


[menu]
    [[menu.main]]
        url = "/"
        name = "Home"
        weight = 1

    [[menu.main]]
        url ="/about"
        name = "About"
        weight = 2

    [[menu.main]]
        url = "/portfolio"
        name = "Portfolio"
        weight = 3

    [[menu.main]]
        url = "/instagram"
        name = "Instagram Feed"
        weight = 4

    [[menu.main]]
        url = "/contact"
        name = "Contact"
        weight = 5
